# Generated by Django 4.2.3 on 2023-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='./users/profile_pic.jpg', null=True, upload_to='users'),
        ),
    ]
