# Generated by Django 4.2.4 on 2023-10-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0006_customuser_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
