# Generated by Django 4.2.4 on 2023-10-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0009_remove_customuser_following_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
