# Generated by Django 4.2.3 on 2023-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Post Sayısı'),
        ),
    ]
