# Generated by Django 4.2.3 on 2023-10-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0005_customuser_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badgecount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rozetler'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followcount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Takipçi Sayısı'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Badge Açıklamaları')),
                ('badgeBronze', models.ImageField(blank=True, default='./badges/badge_bronze.jpg', null=True, upload_to=None)),
                ('badgeSilver', models.ImageField(blank=True, default='./badges/badge_silver.jpg', null=True, upload_to=None)),
                ('badgeGold', models.ImageField(blank=True, default='./badges/badge_gold.jpg', null=True, upload_to=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kullanıcılar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badgeler',
            },
        ),
    ]
