# Generated by Django 4.2.3 on 2023-10-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0007_remove_badges_badgegold_remove_badges_badgesilver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='user',
        ),
    ]
