# Generated by Django 4.2.3 on 2023-10-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0008_remove_badges_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badges',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.RemoveField(
            model_name='badges',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='title',
        ),
        migrations.AddField(
            model_name='badges',
            name='badgeGold',
            field=models.ImageField(blank=True, default='badges/badge_gold.jpg', null=True, upload_to='badges/'),
        ),
        migrations.AddField(
            model_name='badges',
            name='badgeSilver',
            field=models.ImageField(blank=True, default='badges/badge_silver.jpg', null=True, upload_to='badges/'),
        ),
        migrations.AddField(
            model_name='badges',
            name='bronzeAciklama',
            field=models.TextField(blank=True, default='Bronze Badge Description'),
        ),
        migrations.AddField(
            model_name='badges',
            name='bronzeTitle',
            field=models.CharField(default='Bronze Badge Title', max_length=50),
        ),
        migrations.AddField(
            model_name='badges',
            name='goldAciklama',
            field=models.TextField(blank=True, default='Gold Badge Description'),
        ),
        migrations.AddField(
            model_name='badges',
            name='goldTitle',
            field=models.CharField(default='Gold Badge Title', max_length=50),
        ),
        migrations.AddField(
            model_name='badges',
            name='silverAciklama',
            field=models.TextField(blank=True, default='Silver Badge Description'),
        ),
        migrations.AddField(
            model_name='badges',
            name='silverTitle',
            field=models.CharField(default='Silver Badge Title', max_length=50),
        ),
        migrations.AddField(
            model_name='badges',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Kullanıcılar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badges',
            name='badgeBronze',
            field=models.ImageField(blank=True, default='badges/badge_bronze.jpg', null=True, upload_to='badges/'),
        ),
    ]
