# Generated by Django 4.2.3 on 2023-10-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0013_badge_delete_badges_delete_bronzebadge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
    ]
