# Generated by Django 4.2.3 on 2023-10-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0015_remove_customuser_badgecount_remove_customuser_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='user_uuid',
        ),
    ]
