# Generated by Django 4.2.5 on 2023-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_usermodel_isbanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.FileField(default='default_avatar.jpg', upload_to='users/', verbose_name='Avatar Yükleyin'),
        ),
    ]
