# Generated by Django 4.2.5 on 2023-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_usermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.CharField(max_length=150, null=True, verbose_name='Hakkımızda'),
        ),
    ]
