# Generated by Django 4.2.5 on 2023-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_usermodel_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='link',
            new_name='link3',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='link1',
            field=models.URLField(blank=True, default='Link Bulunamadı', null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='link2',
            field=models.URLField(blank=True, default='Link bulunamadı', null=True, verbose_name='Website'),
        ),
    ]
