# Generated by Django 4.2.5 on 2023-10-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='isBanned',
            field=models.BooleanField(default=False, verbose_name='Banlı m?'),
        ),
    ]
