# Generated by Django 4.2.5 on 2023-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_usermodel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Linkler'),
        ),
    ]
