# Generated by Django 4.2.5 on 2023-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_usermodel_link2_alter_usermodel_link3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.FileField(default='default_avatar.jpg', upload_to='uploads', verbose_name='Avatar Yükleyin'),
        ),
    ]
