# Generated by Django 4.2.4 on 2023-10-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
