# Generated by Django 4.2.4 on 2023-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='./users/blank-profile-picture.jpg', upload_to='users'),
        ),
    ]
