# Generated by Django 4.2.4 on 2023-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='./img/users/blank-profile-picture.jpg', upload_to='users'),
        ),
    ]
